dataset: torch/cifar100
num_classes: 100
img_size: 32
mean:
    - 0.5071
    - 0.4867
    - 0.4408
std:
    - 0.2675
    - 0.2565
    - 0.2761
crop_pct: 1.0
scale:
    - 0.8
    - 1.0
interpolation: bicubic
train_interpolation: random
aa: rand-m9-mstd0.5-inc1
mixup: 0.8
mixup_off_epoch: 175
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 1.0
reprob: 0.25
remode: pixel
amp: True
batch_size: 256
lr: 55e-5
min_lr: 1e-5
sched: cosine
weight_decay: 6e-2
epochs: 300
cooldown_epochs: 10
warmup_epochs: 0
warmup_lr: 0.00001
opt: adamw
smoothing: 0.1
workers: 8
use_kd: true
kd_alpha: 4
seed: 3407
checkpoint_hist: 3
# fix_blocksize=-1 represents that the blocksize depends on NAS
# finetune should be false when nas
# lasso_alpha 1e-5 for CIFAR /1e-4 for TinyImageNet
# tau 0.99 is good
finetune: False
lasso_alpha: 0
tau: 1.00
budget: 0.125
fix_blocksize: -1
# 0.15 delta_z 2/4/8/16
# fix_blocksize_list: 2,2,2,2,2,2,8,16,8,8,2,2,16,16,16,16,16,16,2,16,16,16,16,16,4,16,16,16,16,16,16,16
# fix_blocksize_list: 2,2,2,2,2,2,16,16,16,16,2,2,16,16,16,16,16,16,4,16,16,16,16,16,2,16,16,16,16,16,16,16
# b4 delta_z 2/4/8/16
fix_blocksize_list: 2,2,2,2,2,2,2,2,2,2,2,2,8,16,2,16,16,16,2,2,4,16,2,16,2,2,16,16,16,16,2,16
# 0.20
# fix_blocksize_list: 2,2,2,2,2,2,2,16,2,8,2,2,16,16,16,16,16,16,2,2,16,16,16,16,2,16,16,16,16,16,4,16
# 0.125
# fix_blocksize_list: 2,2,2,2,4,2,2,16,16,16,16,2,4,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
log_name: mbv2_c100_b4
teacher: c100_mobilenetv2
teacher_checkpoint: /home/xts/code/njeans/MyViT/pretrained/mbv2_c100.pth.tar
# resume: "/home/xts/code/njeans/MySparsity/Ternary-ViT/output/train/20240130-204808-cifar_cir_nas_mobilenetv2-32/model_best.pth.tar"
initial_checkpoint: /home/xts/code/njeans/MyViT/pretrained/mbv2_c100.pth.tar